from . import donasi
from . import master_program_donasi
from . import master_donatur
from . import master_penerima
from . import master_tipe_penerima
from . import wakaf
from . import master_wakaf_donatur
from . import rab_wakaf
from . import sale_order
from . import purchase_order
from . import res_partner